version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - backend/docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - backend/docker.env
    networks:
    - postgres

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes: 
    - ./frontend/src:/app/frontend/src
    - ./app-types:/app/app-types
    ports: 
    - "3000:3000"
    networks:
    - postgres

  backend:
    container_name: backend
    links:
    - postgres:postgres
    depends_on: 
    - postgres
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes: 
     - ./backend/src:/app/backend/src
     - ./app-types:/app/app-types
    ports: 
    - "3001:3001"
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge
